project:
  type: website
  output-dir: docs

website:
  title: "Knowledge"
  navbar:
    # background: "#102c3c" 
    # background: "#8C1515"
    left:
      - href: index.qmd
        text: Home
      - href: notes.qmd
        text: Stanford Notes
      - href: machine-learning.qmd
        text: Machine Learning
      - href: concepts.qmd
        text: Concepts

format:
  html:
    theme: cosmo  # sandstone, darkly, cosmo, slate, flatly, solar, spacelab, 
    css: styles.css
    toc: true



