project:
  type: website
  output-dir: docs

website:
  title: "Knowledge"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: notes.qmd
        text: Stanford Notes

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



